---
description: Pipeline for parsing Apache Spark node metrics.
processors:
  - set:
      field: ecs.version
      value: '8.11.0'
  - script:
      lang: painless
      description: Copy jolokia.metrics fields to databricks namespace
      if: ctx?.jolokia?.metrics != null
      ignore_failure: true
      source: |
        if (ctx.databricks == null) {
          ctx.databricks = new HashMap();
        }
        if (ctx.jolokia?.metrics?.node != null) {
          ctx.databricks.node = ctx.jolokia.metrics.node;
        }
        if (ctx.jolokia?.metrics?.mbean != null) {
          if (ctx.databricks.node == null) {
            ctx.databricks.node = new HashMap();
          }
          ctx.databricks.node.mbean = ctx.jolokia.metrics.mbean;
        }
  - set:
      field: event.type
      value: [info]
  - set:
      field: event.kind
      value: metric
  - set:
      field: event.module
      value: databricks
  - remove:
      field: jolokia
      ignore_failure: true
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
