---
description: Pipeline for parsing Apache Spark application metrics.
processors:
  - set:
      field: ecs.version
      value: '8.11.0'
  - rename:
      field: jolokia.metrics
      target_field: databricks
      ignore_missing: true
  - set:
      field: event.type
      value: [info]
  - set:
      field: event.kind
      value: metric
  - set:
      field: event.module
      value: databricks
  - script:
      lang: painless
      description: This script will add the name of application under key 'application.name'
      if: ctx?.databricks?.mbean?.contains("name=application") == true
      source: >-
        def bean_name = ctx.databricks.mbean.toString().splitOnToken(".");
        def app_name = "";
        if (bean_name[0].contains("name=application") == true) {
            app_name = bean_name[1] + "." + bean_name[2];
        }
        ctx.databricks.application.name = app_name;
  - rename:
      field: databricks.mbean
      target_field: databricks.application.mbean
      ignore_missing: true
  - remove:
      field:
        - jolokia
      ignore_failure: true
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
